// <auto-generated />
using System;
using EnemPrep.EntityModels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnemPrep.EntityModels.Migrations
{
    [DbContext(typeof(EnemContext))]
    partial class EnemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "color_scheme", new[] { "dark", "light", "os" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "user_role", new[] { "STUDENT", "ADMIN" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "content", "language", new[] { "INGLES", "ESPANHOL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "content", "subject_name", new[] { "linguagens", "ciencias-humanas", "ciencias-natureza", "matematica" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "planning", "day_of_the_week", new[] { "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tracking", "exam_status", new[] { "not_started", "in_progress", "finished", "canceled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CorrectQuestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_questions_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<float?>("EstimatedScore")
                        .HasColumnType("real")
                        .HasColumnName("estimated_score");

                    b.Property<int>("ExamYear")
                        .HasColumnType("integer")
                        .HasColumnName("exam_year");

                    b.Property<int?>("IncorrectQuestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("incorrect_questions_count");

                    b.Property<string>("LanguageChoice")
                        .IsRequired()
                        .HasColumnType("content.language")
                        .HasColumnName("language_choice");

                    b.Property<TimeSpan>("MaxSpentTime")
                        .HasColumnType("interval")
                        .HasColumnName("max_spent_time");

                    b.Property<int>("QuestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("questions_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("tracking.exam_status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title");

                    b.Property<TimeSpan?>("TotalSpentTime")
                        .HasColumnType("interval")
                        .HasColumnName("total_spent_time");

                    b.Property<int?>("UnsolvedQuestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("unsolved_questions_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ExamId")
                        .HasName("exam_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("exam", "tracking");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.ExamQuestion", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<char?>("ChosenAlternative")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("chosen_alternative");

                    b.Property<char>("CorrectAlternative")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("correct_alternative");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("interval")
                        .HasColumnName("time_spent");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ExamId", "QuestionId")
                        .HasName("exam_question_pk");

                    b.HasIndex("QuestionId");

                    b.ToTable("exam_question", "tracking");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.ExamSubject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SubjectId", "ExamId")
                        .HasName("pk_exam_subject");

                    b.HasIndex("ExamId");

                    b.ToTable("exam_subject", "tracking");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ApiIndex")
                        .HasColumnType("integer")
                        .HasColumnName("api_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Language")
                        .HasColumnType("content.language")
                        .HasColumnName("language");

                    b.Property<Guid>("PostedById")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by_id");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("QuestionId")
                        .HasName("question_pkey");

                    b.HasIndex("PostedById");

                    b.HasIndex("SubjectId");

                    b.ToTable("question", "content");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'Cronograma Semanal'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ScheduleId")
                        .HasName("schedule_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("schedule", "planning");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.ScheduleSubject", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SubjectOrder")
                        .HasColumnType("integer")
                        .HasColumnName("subject_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasColumnType("planning.day_of_the_week")
                        .HasColumnName("weekday");

                    b.HasKey("ScheduleId", "SubjectId")
                        .HasName("pk_schedule_subject");

                    b.HasIndex("SubjectId");

                    b.ToTable("schedule_subject", "planning");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.SolvedQuestion", b =>
                {
                    b.Property<Guid>("SolvedQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("solved_question_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<char?>("ChosenAlternative")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("chosen_alternative");

                    b.Property<char>("CorrectAlternative")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("correct_alternative");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionYear")
                        .HasColumnType("integer")
                        .HasColumnName("question_year");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("interval")
                        .HasColumnName("time_spent");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SolvedQuestionId")
                        .HasName("solved_question_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("solved_question", "tracking");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Name")
                        .HasColumnType("content.subject_name")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SubjectId")
                        .HasName("subject_pkey");

                    b.ToTable("subject", "content");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_password");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_private");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_image");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserRole")
                        .HasColumnType("auth.user_role")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("user_pkey");

                    b.HasIndex(new[] { "Username" }, "user_username_key")
                        .IsUnique();

                    b.ToTable("user", "auth");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.UserGoal", b =>
                {
                    b.Property<Guid>("UserGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_goal_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<float>("CutOffScore")
                        .HasColumnType("real")
                        .HasColumnName("cut_off_score");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("university_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserGoalId")
                        .HasName("user_goal_pkey");

                    b.HasIndex(new[] { "UserId" }, "unique_goal")
                        .IsUnique();

                    b.ToTable("user_goal", "planning");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.UserPreference", b =>
                {
                    b.Property<Guid>("UserPreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_preferences_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorScheme")
                        .IsRequired()
                        .HasColumnType("auth.color_scheme")
                        .HasColumnName("color_scheme");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExamLanguage")
                        .IsRequired()
                        .HasColumnType("content.language")
                        .HasColumnName("exam_language");

                    b.Property<int>("QuestionsPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("questions_per_day");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserPreferencesId")
                        .HasName("user_preferences_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_preferences", "auth");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_level");

                    b.Property<int>("ExperiencePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_points");

                    b.Property<DateTime>("LastActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_date")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("StreakCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("streak_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserBio")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_bio");

                    b.HasKey("UserId")
                        .HasName("user_profile_pkey");

                    b.ToTable("user_profile", "tracking");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Exam", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.User", "User")
                        .WithMany("Exams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.ExamQuestion", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_question_exam_id_fkey");

                    b.HasOne("EnemPrep.EntityModels.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_question_question_id_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.ExamSubject", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.Exam", "Exam")
                        .WithMany("ExamSubjects")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_subject_exam_id_fkey");

                    b.HasOne("EnemPrep.EntityModels.Models.Subject", "Subject")
                        .WithMany("ExamSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("exam_subject_subject_id_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Question", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.User", "PostedBy")
                        .WithMany("Questions")
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.HasOne("EnemPrep.EntityModels.Models.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subject_id");

                    b.Navigation("PostedBy");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Schedule", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.User", "User")
                        .WithMany("Schedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.ScheduleSubject", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.Schedule", "Schedule")
                        .WithMany("ScheduleSubjects")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("schedule_subject_schedule_id_fkey");

                    b.HasOne("EnemPrep.EntityModels.Models.Subject", "Subject")
                        .WithMany("ScheduleSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("schedule_subject_subject_id_fkey");

                    b.Navigation("Schedule");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.SolvedQuestion", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.Question", "Question")
                        .WithMany("SolvedQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("solved_question_question_id_fkey");

                    b.HasOne("EnemPrep.EntityModels.Models.User", "User")
                        .WithMany("SolvedQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("solved_question_user_id_fkey");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.UserGoal", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.User", "User")
                        .WithOne("UserGoal")
                        .HasForeignKey("EnemPrep.EntityModels.Models.UserGoal", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.UserPreference", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.UserProfile", b =>
                {
                    b.HasOne("EnemPrep.EntityModels.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("EnemPrep.EntityModels.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_profile_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamSubjects");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Question", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("SolvedQuestions");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Schedule", b =>
                {
                    b.Navigation("ScheduleSubjects");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.Subject", b =>
                {
                    b.Navigation("ExamSubjects");

                    b.Navigation("Questions");

                    b.Navigation("ScheduleSubjects");
                });

            modelBuilder.Entity("EnemPrep.EntityModels.Models.User", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Questions");

                    b.Navigation("Schedules");

                    b.Navigation("SolvedQuestions");

                    b.Navigation("UserGoal");

                    b.Navigation("UserPreferences");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
