import type { Metadata } from "next";
import { Inter, Merriweather, Fira_Code } from "next/font/google";
import "./globals.css";
import React from "react";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "@/app/StoreProvider";
import AuthLinks from "@/components/AuthLinks";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<Readonly<IRootLayoutProps>> = ({ children }) => {
  return (
    <html
      lang="pt-BR"
      className={cn(fontSans.variable, fontSerif.variable, fontMono.variable)}
      suppressHydrationWarning
    >
      <body
        className="bg-background dark text-foreground selection:bg-primary/20 antialiased"
        suppressHydrationWarning
      >
        <StoreProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="flex h-screen flex-col overflow-hidden">
              <header className="border-sidebar-border bg-background/50 background-blur-sm flex h-14 shrink-0 items-center gap-2 border-b px-4">
                <SidebarTrigger />
                <div className="flex w-full items-center justify-between">
                  <span className="text-muted-foreground text-sm font-medium">
                    Área Interna
                  </span>
                  <AuthLinks />
                </div>
              </header>

              <main className="flex h-full flex-col items-center justify-start overflow-y-auto p-6 focus:outline-none">
                {children}
              </main>
              <Toaster />
            </SidebarInset>
          </SidebarProvider>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
