import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import {SidebarInset, SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";
import {cn} from "@/lib/utils";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

const RootLayout : React.FC<Readonly<IRootLayoutProps>> = ({ children }) => {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="bg-background text-foreground antialiased selection:bg-primary/20">
        <SidebarProvider>
          <AppSidebar />

          <SidebarInset className="flex flex-col h-screen overflow-hidden">
            <header className="flex h-14 shrink-0 items-center gap-2 border-b border-sidebar-border px-4 bg-background/50 background-blur-sm">
              <SidebarTrigger />
              <div className="w-full flex justify-between items-center">
                <span className="text-sm font-medium text-muted-foreground">Área Interna</span>
                <div className="flex gap-x-4 mr-4">
                  <Link href="/login">Login</Link>
                  <Link href="/register">Cadastre-se</Link>
                </div>
              </div>
            </header>

            <main className="flex flex-col items-center justify-center h-full overflow-y-auto p-6 focus:outline-none">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}

export default RootLayout;
